name: 🧭 Advancement Idea
description: Submit a new advancement idea
labels: ["advancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe your advancement
      description: Trigger criteria, name, description, icon, parent, etc.
      placeholder: Do this with that and the other
    validations:
      required: true
  - type: dropdown
    id: tab
    attributes:
      label: Advancement tab
      options:
        - Random Item Skyblock
        - Special Items
        - Alchemy Items
    validations:
      required: true
  - type: markdown
    attributes:
      value: <br> Thank you for suggesting this advancement! We'll take a look as soon as possible.