name: 🐛 Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe your issue *and* expected results
      placeholder: When I click here this happens instead of that
    validations:
      required: true
  - type: markdown
    attributes:
      value: _(attach or link any images or videos above)_
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to page
        2. Click here
        3. Click there
    validations:
      required: true
  - type: input
    id: risver
    attributes:
      label: Random Item Skyblock Version
      placeholder: 3.0.0  (visible in "/reload" message)
    validations:
      required: true
  - type: input
    id: mcver
    attributes:
      label: Minecraft Version
      placeholder: 1.21.4  (visible in F3 menu)
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Vanilla
        - Fabric
        - Forge
        - Paper
        - Other (list above!)
    validations:
      required: true
  - type: dropdown
    id: host
    attributes:
      label: Host type
      options:
        - Singleplayer world
        - Multiplayer server
    validations:
      required: true
  - type: input
    id: mods
    attributes:
      label: Other mods
      placeholder: Please list any other mods (especially server side) you may have installed
  - type: markdown
    attributes:
      value: <br> Thank you for reporting this issue! We'll take a look as soon as possible.