name: 🐛 Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe your issue *and* expected result
      placeholder: When I click here this happens instead of that
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to page
        2. Click here
        3. Click there
    validations:
      required: true
  - type: textarea
    id: media
    attributes:
      label: Screenshots or videos (optional)
      placeholder: Paste images or video links here
  - type: input
    id: risver
    attributes:
      label: Random Item Skyblock Version
      placeholder: 3.0.0  (visible in "/reload" message)
    validations:
      required: true
  - type: input
    id: mcver
    attributes:
      label: Minecraft Version
      placeholder: Vanilla 1.21.4  |  Forge 1.20.1  |  Fabric 1.19.2  |  Paper 1.16.5
    validations:
      required: true
  - type: checkboxes
    id: environment
    attributes:
      label: Environment (check all that apply)
      options:
        - label: Modded?
        - label: Vanilla?
        - label: Paper server?
        - label: Multiplayer? (server)
        - label: Singleplayer? (world)
  - type: input
    id: mods
    attributes:
      label: Other mods
      placeholder: Please list any other mods (especially server side) you may have installed
  - type: markdown
    attributes:
      value: <br> _Thank you for reporting this issue! We'll take a look as soon as possible._